### PR TITLE
Branch samad

### PR DESCRIPTION
**Pull request by samad2022**
Hi Ihtesham,

Please see new codes in class Samad and approve.
Thanks,
Samad

### CODE REVIEW

**Comment by ihtesham-github** [comment]
Hi Samad,
Checked. Please rebase and merge.

**Comment by samad2022** [comment]
Hi Ihtesham,
This branch cannot be rebased due to conflicts.
>>>Samad

**Comment by ihtesham-github** [comment]
Hi Samad,
Ok, merge.
__Ihtesham

**Comment by samad2022** [comment]
Hi Ihtesham,
Merged. Thank you,
__Samad

**Pull request merged**
